const baseSkill = require("../../common/baseSkill");
//Excel based Common Functionality goes here 
module.exports = class ExcelBaseSkill extends baseSkill{
//this function moved to  Base Excel Skill 
// Sheet number still hardcoded, should be generated by the component handler
    createImageJson (paramValueObj){
        
        var finalObject = {};
        finalObject['folderPath'] = paramValueObj["sheets"][0]["path"];
        var sheetArr = []

        for(var iterator = 0 ; iterator < paramValueObj["sheets"].length; ++iterator){
            sheetArr[iterator] = {};
            sheetArr[iterator]['sheetNo'] = 1;
            sheetArr[iterator]['gridImg'] = paramValueObj["sheets"][iterator].gridImage.name
            sheetArr[iterator]['rowImg'] = paramValueObj["sheets"][iterator].rowImage.name;
            sheetArr[iterator]['colImg'] = paramValueObj["sheets"][iterator].cellImage.name;
            sheetArr[iterator]['cellImg'] = paramValueObj["sheets"][iterator].columnImage.name;
        }
        finalObject['sheetImages'] = sheetArr;
        finalObject = JSON.stringify(finalObject);
        return finalObject;
    }
}
