const baseSkill = require("../../common/baseSkill");

//Excel based Common Functionality goes here 
module.exports = class ExcelBaseSkill extends baseSkill{
//this function moved to  Base Excel Skill 
// Sheet number still hardcoded, should be generated by the component handler
    createImageJson (paramValueArr){

        var finalObject = {};
        finalObject['folderPath'] = paramValueArr[0].path;
        var sheetArr = []

        for(iterator = 0 ; iterator < paramValueArr[0].length; ++iterator){
            sheetArr[iterator] = {};
            sheetArr[iterator]['sheetNo'] = 1;
            sheetArr[iterator]['gridImg'] = paramValueArr[0][iterator].gridImage.name;
            sheetArr[iterator]['rowImg'] = paramValueArr[0][iterator].rowImage.name;
            sheetArr[iterator]['colImg'] = paramValueArr[0][iterator].cellImage.name;
            sheetArr[iterator]['cellImg'] = paramValueArr[0][iterator].columnImage.name;
        }
        finalObject['sheetImages'] = sheetArr;
        finalObject = JSON.stringify(finalObject);
        return finalObject;
    }
}
